'use client';
import {AdminAssets} from './assets';
import {useCallback, useEffect, useState} from 'react';
import {formatUnits, keccak256, toHex} from 'viem';
import type {AdminAccountView} from '@/lib/admin/model';
import {OPERATOR_ACTIONS} from '@/lib/admin/policy';
import {AdminTeam} from './team';
import type {SlotSnapshot, GameView} from '@/lib/slot/reader';
import {ADMIN_ACTIONS, ADMIN_TARGETS, type AdminAction} from '@/lib/slot/actions';
import {SYMBOLS} from '@/lib/slot/config';
import {TransactionConfirmation} from '@/lib/slot/transaction-review';
import {useContractTransaction} from '@/lib/slot/use-transaction';

type Data = SlotSnapshot & {keeper: {configured: boolean; address: string | null; lastTick: number; lastBlock: string; error: string; canStartFreeSpin: boolean; balanceWei: string; pendingTransaction: string | null}};
type Tab = 'overview' | 'games' | 'prizes' | 'operations' | 'wallet' | 'swap' | 'inventory';
const navigation: {id:Tab; icon:string; label:string}[] = [{id:'overview',icon:'◈',label:'Overview'},{id:'games',icon:'▤',label:'Onchain spins'},{id:'prizes',icon:'★',label:'Prizes and reserves'},{id:'operations',icon:'⊙',label:'Operations'},{id:'swap',icon:'⇄',label:'Swap'},{id:'inventory',icon:'▦',label:'Inventory'},{id:'wallet',icon:'◇',label:'Admin wallet'}];
const gameLabels: Record<string,string> = {waiting:'Waiting for block',revealable:'Reveal available',expired:'Reveal expired',won:'Won',lost:'No prize',invalidated:'Invalidated'};
const short = (value:string) => value.slice(0,6)+' ··· '+value.slice(-6);
const usdc = (value:string) => formatUnits(BigInt(value),6);
const displayBalance = (value:string|null) => {if(value===null)return '—';const [integer,decimals='']=value.split('.');return integer+'.'+decimals.padEnd(2,'0');};
const transactionLink = (hash:string) => 'https://basescan.org/tx/'+hash;
export function AdminWorkspace({account, identity, error, busy, onRefresh, onLogout}: {
  account:AdminAccountView & {wallet:NonNullable<AdminAccountView['wallet']>}; identity:string; error:string; busy:boolean; onRefresh:()=>void; onLogout:()=>void;
}) {
  const [swapBusy,setSwapBusy]=useState(false);
  const wallet=account.wallet, transaction=useContractTransaction(wallet.address,account.userId);
  const walletBalance=displayBalance(wallet.balance.amount);
  const [tab,setTab]=useState<Tab>('overview'), [data,setData]=useState<Data|null>(null), [configured,setConfigured]=useState<boolean|null>(null), [loadError,setLoadError]=useState('');
  const [history,setHistory]=useState<GameView[]>([]), [historyCursor,setHistoryCursor]=useState<string|undefined>(), [nextCursor,setNextCursor]=useState('0');
  const [selected,setSelected]=useState<GameView|null>(null), [action,setAction]=useState<AdminAction>('pause'), [args,setArgs]=useState<string[]>([]), [copied,setCopied]=useState(false);
  const reload=useCallback(async()=>{
    try {
      const response=await fetch('/api/contract?view=admin&player='+wallet.address,{cache:'no-store',signal:AbortSignal.timeout(25000)});
      const value=await response.json(); if(!response.ok)throw new Error(value.error||'Onchain read unavailable.');
      setConfigured(value.configured);setData(value.configured?value:null);setLoadError('');
    } catch(cause){setLoadError(cause instanceof Error?cause.message:'Onchain connection lost.');}
  },[wallet.address]);
  useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;async function poll(){await reload();if(!stopped)timer=setTimeout(poll,10000);}void poll();return()=>{stopped=true;clearTimeout(timer);};},[reload]);
  useEffect(()=>{if(transaction.confirmed){void reload();onRefresh();}},[transaction.confirmed]);
  useEffect(()=>{
    if(!data||tab!=='games')return;
    let cancelled=false;
    fetch('/api/contract?view=history'+(historyCursor?'&before='+historyCursor:''),{cache:'no-store',signal:AbortSignal.timeout(25000)}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!cancelled){setHistory(value.games);setNextCursor(value.next);setSelected(previous=>previous?value.games.find((game:GameView)=>game.id===previous.id)||previous:null);}}).catch(cause=>{if(!cancelled)setLoadError(cause instanceof Error?cause.message:'History unavailable.');});
    return()=>{cancelled=true;};
  },[tab,historyCursor,data?.block,transaction.confirmed]);
  const definition=ADMIN_ACTIONS.find(item=>item.name===action)!;
  const target=ADMIN_TARGETS.find(item=>item.id===definition.target)!;
  const visibleActions=ADMIN_ACTIONS.filter(item=>account.role==='owner'||OPERATOR_ACTIONS.includes(item.name));
  const permitted=!!data&&account.operationsEnabled&&(action!=='mintERC1155'||!!account.mintEnabled)&&(account.role==='owner'||OPERATOR_ACTIONS.includes(action))&&(definition.role==='any'||definition.role==='owner'&&data.permissions?.isOwner||definition.role==='manager'&&data.permissions?.manager||definition.role==='treasurer'&&data.permissions?.treasurer||definition.role==='pauser'&&data.permissions?.pauser);
  function chooseAction(value:AdminAction,preset:string[]=[]){setAction(value);setArgs(preset);setTab('operations');}
  async function copy(){try{await navigator.clipboard.writeText(wallet.address);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setLoadError('Select and copy the full address.');}}
  function table(rows:GameView[]){return <div className="session-table-wrap"><table className="session-table"><thead><tr><th>Spin / wallet</th><th>Type</th><th>Status</th><th>Actual prize</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{rows.map(game=><tr key={game.id}><td><strong>#{game.id}</strong><span>{short(game.player)}</span></td><td>{game.freeSpin?'FREE SPIN':'USDC'}</td><td><span className={'session-badge '+(game.pending?'active':game.won?'active':game.invalidated?'expired':'ended')}>{gameLabels[game.status]}</span></td><td>{game.payout?game.payout.formattedAmount+' '+(game.payout.kind===3?'free spin':game.payout.tokenSymbol||SYMBOLS[game.winningSymbol]):'—'}</td><td><button className="table-action" aria-label={'Spin details '+game.id} onClick={()=>setSelected(game)}>↗</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-result"><h3>No spins yet.</h3><p>Spins appear after onchain confirmation.</p></div>}</div>;}
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="admin-brand" href="/admin"><span aria-hidden="true">$</span><b>WALL STREET<br/>SLOT<sup>™</sup></b></a><span className="sidebar-label">CONTROL ROOM / ONCHAIN</span><nav aria-label="Admin sections">{navigation.map(item=><button key={item.id} aria-current={tab===item.id?'page':undefined} className={tab===item.id?'selected':''} onClick={()=>setTab(item.id)}><span aria-hidden="true">{item.icon}</span>{item.label}{tab===item.id&&<i/>}</button>)}</nav><div className="sidebar-foot"><div className="operator-mini"><span>↗</span><div><b>{account.role==='owner'?'Wallet owner':'Collaborator'}</b><small>{short(wallet.address)}</small></div></div><button className="sidebar-logout" onClick={onLogout}>Sign out <span>↗</span></button><a href="/">Open the terminal ↗</a></div></aside>
    <main className="admin-main"><header className="admin-topbar"><span>OPERATOR SPACE <b>/ {navigation.find(item=>item.id===tab)?.label.toUpperCase()}</b></span><span className="real-badge">● SHARED WALLET</span></header><div className="admin-page-heading"><div><span className="eyebrow">YOUR FLOOR. FULLY ONCHAIN.</span><h1>{tab==='overview'?'All in place.':tab==='games'?'Every spin, onchain.':tab==='prizes'?'Luck pays a prize.':tab==='operations'?'At the controls.':tab==='swap'?'From crypto to prizes.':tab==='inventory'?'Your stock of luck.': 'The wallet of your floor.'}</h1><p>{tab==='wallet'?'One address, one balance and shared top-ups. On Base.':tab==='swap'?'Buy tokens from the shared wallet and prepare the next prizes.':tab==='inventory'?'Tokens in the wallet and prizes to deposit into the slot, on Base.':'Status, permissions and results read straight from the contract.'}</p></div><span className="heading-star" aria-hidden="true">★</span></div>
      {(error||loadError)&&<div className="admin-error" role="alert">{error||loadError}<button className="admin-text" disabled={busy} onClick={()=>{void reload();onRefresh();}}>Refresh</button></div>}
      {transaction.error&&<div className="admin-error" role="alert">{transaction.error}</div>}
      {transaction.pending&&<div className="admin-feedback" role="status"><span>Request under verification{transaction.gasToken?' · gas '+transaction.gasToken:''}. {transaction.hash&&<a href={transactionLink(transaction.hash)} target="_blank" rel="noreferrer">View on Base ↗</a>}</span><button className="admin-text" disabled={transaction.busy} onClick={()=>void transaction.check()}>Check</button></div>}
      {data?.keeper.pendingTransaction&&<div className="admin-feedback" role="status">Keeper wallet · transaction pending. <a href={transactionLink(data.keeper.pendingTransaction)} target="_blank" rel="noreferrer">View on Base ↗</a></div>}
      {!['wallet','swap','inventory'].includes(tab)&&!data&&<section className="admin-card contract-empty"><span className="eyebrow">{configured===false?'READY FOR DEPLOY':'ONCHAIN CONNECTION'}</span><h2>{configured===false?'Let us link the machine.':'Reading the contract…'}</h2><p>{configured===false?'The contract is not deployed yet. After deploy, the address and starting block enable reads, spins and management.':'Waiting for the configuration read.'}</p><p className="fine-print">Your Privy wallet is already available. Machine data will appear from the blockchain.</p><button className="admin-secondary" onClick={()=>setTab('wallet')}>Open your wallet ↗</button></section>}
      {data&&tab==='overview'&&<>
        <div className="chain-strip"><span className="real-badge">● BASE</span><code>{short(data.address)}</code><span>Block {data.block}</span><button className="admin-text" onClick={()=>void reload()}>Refresh ↻</button></div>
        <div className="metrics"><article><span className="metric-label">MACHINE <i>↗</i></span><strong>{data.settings.paused?'Paused':!data.funding?'Checking':!data.funding.ready?'Restock needed':'Live'}<span className={'metric-dot '+(data.settings.paused?'paused':'')}/></strong><small>{data.settings.configuredPrizeCount} symbols configured</small></article><article><span className="metric-label">TICKET <i>◇</i></span><strong>{usdc(data.settings.ticketPrice)}<small>USDC</small></strong><small>Current onchain price</small></article><article><span className="metric-label">PENDING SPINS <i>▤</i></span><strong>{data.settings.activeRoundCount}</strong><small>{(BigInt(data.settings.nextGameId)-1n).toString()} spins in total</small></article><article className="real-metric"><span className="metric-label">SHARED BALANCE <i>◇</i></span><strong>{walletBalance}<small>USDC</small></strong><button onClick={()=>setTab('wallet')}>Open wallet on Base ↗</button></article></div>
        <div className="overview-columns"><section className="admin-card"><div className="card-heading"><h2>Machine and odds</h2><span className="real-badge">ONCHAIN</span></div><div className="settings-facts"><div><span>Table complete</span><b>{data.settings.totalOutcomeWeight/10}% / 100%</b></div><div><span>No prize</span><b>{data.settings.noWinWeight/10}%</b></div><div><span>Wait</span><b>{data.settings.revealDelayBlocks} blocks</b></div><div><span>Reveal window</span><b>{data.settings.revealWindowBlocks} blocks</b></div><div><span>Catalog version</span><b>{data.settings.catalogVersion}</b></div></div><button className="admin-secondary" disabled={!account.operationsEnabled||!data.permissions?.pauser} onClick={()=>chooseAction(data.settings.paused?'unpause':'pause')}>{data.settings.paused?'Resume':'Pause'} ↗</button></section>
        <section className="admin-card keeper-card"><div className="card-heading"><h2>Keeper wallet</h2><span className={'session-badge '+(data.keeper.configured?'active':'expired')}>{data.keeper.configured?'Configured':'To configure'}</span></div><p>Settles reveals and starts free spins for players.</p><code>{data.keeper.address||'SLOT_BACKEND_PRIVATE_KEY not set'}</code><div className="settings-facts"><div><span>Gas balance</span><b>{formatUnits(BigInt(data.keeper.balanceWei),18)} ETH</b></div><div><span>Last checked block</span><b>{data.keeper.lastBlock}</b></div><div><span>Free-spin role</span><b>{data.keeper.canStartFreeSpin?'Enabled':'GAME_MANAGER_ROLE missing'}</b></div></div>{data.keeper.error&&<p className="admin-error">{data.keeper.error}</p>}{data.keeper.address&&account.role==='owner'&&data.permissions?.isOwner&&!data.keeper.canStartFreeSpin&&<button className="admin-secondary" onClick={()=>chooseAction('grantRole',[keccak256(toHex('GAME_MANAGER_ROLE')),data.keeper.address!])}>Authorize keeper free spins ↗</button>}</section></div>
        <section className="admin-card"><div className="card-heading"><h2>Shared wallet permissions</h2><span className="real-badge">READ FROM THE CONTRACT</span></div><div className="role-chips">{['isOwner','manager','treasurer','pauser'].map(role=><span key={role} className={data.permissions?.[role as keyof NonNullable<Data['permissions']>]?'enabled':''}>{role==='isOwner'?'Owner':role}</span>)}</div><p className="fine-print">Every operation needs the matching onchain role and a confirmation from your Privy wallet.</p></section>
      </>}
      {data&&tab==='games'&&<section className="admin-card"><div className="card-heading"><h2>Spin log</h2><span className="real-badge">CONTRACT + EVENTS</span></div>{table(history)}<div className="history-pagination"><button className="admin-text" disabled={!historyCursor} onClick={()=>setHistoryCursor(undefined)}>← Newest</button><button className="admin-text" disabled={BigInt(nextCursor)<=1n} onClick={()=>setHistoryCursor(nextCursor)}>Older ↗</button></div></section>}
      {data&&tab==='prizes'&&<><div className="chain-strip"><span>Total probability: <b>{data.settings.totalOutcomeWeight/10}%</b></span><span>No prize: <b>{data.settings.noWinWeight/10}%</b></span></div><div className="prize-grid">{data.catalog.map(prize=>{const stock=data.inventory.find(value=>value.symbol===prize.symbol);return <article className="admin-card prize-card" key={prize.symbol}><header><img src={'/symbols/symbol-'+prize.symbol+'.svg'} alt=""/><div><span className="eyebrow">SYMBOL {prize.symbol}</span><h2>{SYMBOLS[prize.symbol]}</h2><span className="session-badge">{prize.kind===1?'ERC20':prize.kind===2?'ERC1155':'FREE SPIN'}</span></div></header><div className="settings-facts"><div><span>Odds 3/5 · 5/5</span><b>{prize.threeMatchWeight/10}% · {prize.fiveMatchWeight/10}%</b></div><div><span>5/5 prize (base units)</span><b>{prize.fiveMatchAmount}</b></div><div><span>3/5 prize (base units)</span><b>{prize.threeMatchWeight?prize.kind===1?(BigInt(prize.fiveMatchAmount)/2n).toString():prize.fiveMatchAmount:'—'}</b></div>{stock&&<><div><span>Total reserve · reserved</span><b>{stock.balance} · {stock.reserved}</b></div><div><span>Available (base units)</span><b>{stock.available}</b></div></>}</div>{prize.kind!==3&&<code>{prize.token}{prize.kind===2?' / ID '+prize.tokenId:''}</code>}<button className="admin-text" disabled={!account.operationsEnabled||!data.permissions?.manager} onClick={()=>chooseAction('configurePrize',[String(prize.symbol),String(prize.kind),prize.token,prize.tokenId,prize.fiveMatchAmount,String(prize.threeMatchWeight),String(prize.fiveMatchWeight)])}>Edit prize ↗</button></article>;})}</div>{!data.catalog.length&&<section className="admin-card"><h2>The catalog is empty.</h2><p>Configure at least three symbols and complete the total to 100% before opening spins.</p><button className="admin-secondary" disabled={!account.operationsEnabled||!data.permissions?.manager} onClick={()=>chooseAction('configurePrize')}>Configure a prize ↗</button></section>}</>}
      {data&&tab==='operations'&&<div className="operations-layout"><section className="admin-card settings-card"><div className="card-heading"><h2>Onchain operation</h2><span className="real-badge">PRIVY ADMIN</span></div><label className="operation-label" htmlFor="admin-action">What do you want to do?</label><select id="admin-action" value={action} disabled={transaction.busy||transaction.pending||swapBusy} onChange={event=>chooseAction(event.target.value as AdminAction)}>{ADMIN_TARGETS.map(group=>{const items=visibleActions.filter(item=>item.target===group.id);return items.length?<optgroup key={group.id} label={group.label}>{items.map(item=><option key={item.name} value={item.name}>{item.label}</option>)}</optgroup>:null;})}</select><p className="operation-target-note"><b>{target.label}</b> · {target.note}</p><form onSubmit={event=>{event.preventDefault();void transaction.execute(action,args).catch(()=>{});}}>{definition.fields.map((label,index)=><label className="operation-field" key={action+index}>{label}<input value={args[index]||''} required disabled={transaction.busy||transaction.pending||swapBusy} onChange={event=>setArgs(previous=>{const next=[...previous];next[index]=event.target.value.trim();return next;})}/></label>)}{!permitted&&<p className="admin-error">Your access or the wallet roles do not allow this operation.</p>}<div className="operation-review"><span className="eyebrow">SIGN FROM YOUR WALLET</span><code>{short(wallet.address)}</code><p>{definition.label} · {target.label} · Base network</p><small>{data.gasMode==='usdc'?'Gas in USDC from your wallet; ETH fallback if USDC is not enough.':'Gas is paid in ETH from your wallet.'}</small></div><button className="admin-primary" type="submit" disabled={!permitted||transaction.busy||transaction.pending||swapBusy||!!loadError}>{transaction.busy?'Confirming…':'Simulate and confirm with Privy'} <span>↗</span></button></form></section><section className="admin-card operation-notes"><span className="eyebrow">FROM THE CONTRACT</span><h2>Every change is a transaction.</h2><p>Price, prizes and timing can only change with no pending spins. Withdrawals also require a pause.</p><p>Weights must add up to 1000: one unit is 0.1%. Token amounts are in the base units indicated by the fields.</p><h3>bytes32 roles</h3>{['GAME_MANAGER_ROLE','TREASURER_ROLE','PAUSER_ROLE'].map(role=><div className="role-value" key={role}><span>{role}</span><code>{keccak256(toHex(role))}</code></div>)}<p>Owner: <code>{data.permissions?.owner}</code></p>{data.pendingOwner&&data.pendingOwner.address!=='0x0000000000000000000000000000000000000000'&&<p>Transfer pending to <code>{data.pendingOwner.address}</code>, acceptable from timestamp {data.pendingOwner.schedule}.</p>}</section></div>}
      {tab==='wallet'&&<div className="wallet-layout"><section className="admin-card admin-wallet-card"><div className="card-heading"><h2>Shared wallet</h2><span className="real-badge">● LIVE · BASE</span></div><span className="eyebrow">AVAILABLE BALANCE</span><div className="admin-wallet-balance">{walletBalance} <span>USDC</span></div><p className="balance-freshness">{error||wallet.balance.stale?'Last known balance · update pending':'Balance read on the Base network'}</p><button className="admin-text" disabled={busy} onClick={onRefresh}>{busy?'Refreshing…':'Refresh balance ↻'}</button><div className="account-details"><span>YOUR PRIVY LOGIN</span><p>{identity}</p><span>WALLET ADDRESS</span><code>{wallet.address}</code><button className="admin-secondary" onClick={()=>void copy()}>{copied?'Address copied ✓':'Copy address ↗'}</button></div><p className="fine-print">This wallet signs the team operations. The Inventory section shows wallet and contract balances side by side, with prize deposits and mint.</p></section><section className="admin-card admin-receive"><span className="eyebrow">USDC / BASE MAINNET</span><h2>Top up.</h2><p>Receive USDC on the Base network.</p><img src={wallet.depositQr} width={220} height={220} alt="QR code of the admin wallet address on Base"/><code>{wallet.address}</code><span className="receive-network">● BASE · USDC</span><p className="fine-print">The deposit reaches the shared wallet and is available to the other authorized admins too.</p></section></div>}
      <AdminAssets tab={tab} address={wallet.address} userId={account.userId} slot={data} contractBusy={transaction.busy||transaction.pending} canDeposit={account.operationsEnabled} onDeposit={transaction.execute} onRefresh={onRefresh} onSwapBusy={setSwapBusy} onConfigure={asset=>chooseAction('configurePrize',[String(asset.symbol),'1',asset.address,'0','','',''])}/>
      {tab==='wallet'&&<AdminTeam account={account} onRefresh={onRefresh}/>}
      <footer className="admin-footer">WALL STREET SLOT / CONTROL ROOM <span>EST. 2026 ★</span></footer>
    </main>
    <TransactionConfirmation review={transaction.review} onDecision={transaction.decide}/>
    {selected&&<div className="admin-modal-backdrop"><section className="admin-session-dialog" role="dialog" aria-modal="true" aria-labelledby="game-detail-title" onKeyDown={event=>{if(event.key==='Escape')setSelected(null);if(event.key==='Tab'){const links=event.currentTarget.querySelectorAll<HTMLElement>('button,a');const first=links[0],last=links[links.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}}><div className="card-heading"><span className="real-badge">ONCHAIN</span><button className="table-action" autoFocus aria-label="Close details" onClick={()=>setSelected(null)}>×</button></div><h2 id="game-detail-title">Spin #{selected.id}</h2><code className="game-player-address">{selected.player}</code><div className="settings-facts"><div><span>Status</span><b>{gameLabels[selected.status]}</b></div><div><span>Target / deadline</span><b>{selected.targetBlock} / {selected.revealDeadline}</b></div><div><span>Catalog</span><b>v{selected.catalogVersion}</b></div><div><span>Prize</span><b>{selected.payout?selected.payout.formattedAmount+' '+(selected.payout.tokenSymbol||SYMBOLS[selected.winningSymbol]):'—'}</b></div></div>{selected.hasResult&&selected.confirmed&&<div className="result-mini-grid">{selected.symbols.map((symbol,index)=><img key={index} src={'/symbols/symbol-'+symbol+'.svg'} alt={SYMBOLS[symbol]}/>)}</div>}{selected.transactionHash&&<a className="admin-text" href={transactionLink(selected.transactionHash)} target="_blank" rel="noreferrer">Reveal on BaseScan ↗</a>}</section></div>}
  </div>;
}
