'use client';
import {AdminAssets} from './assets';
import {useCallback, useEffect, useState} from 'react';
import {formatUnits, keccak256, toHex} from 'viem';
import type {AdminAccountView} from '@/lib/admin/model';
import {OPERATOR_ACTIONS} from '@/lib/admin/policy';
import {AdminTeam} from './team';
import type {SlotSnapshot, GameView} from '@/lib/slot/reader';
import {ADMIN_ACTIONS, ADMIN_TARGETS, type AdminAction} from '@/lib/slot/actions';
import {SYMBOLS} from '@/lib/slot/config';
import {TransactionConfirmation} from '@/lib/slot/transaction-review';
import {useContractTransaction} from '@/lib/slot/use-transaction';

type Data = SlotSnapshot & {keeper: {configured: boolean; address: string | null; lastTick: number; lastBlock: string; error: string; canStartFreeSpin: boolean; balanceWei: string; pendingTransaction: string | null}};
type Tab = 'overview' | 'games' | 'prizes' | 'operations' | 'wallet' | 'swap' | 'inventory';
const navigation: {id:Tab; icon:string; label:string}[] = [{id:'overview',icon:'◈',label:'Panoramica'},{id:'games',icon:'▤',label:'Giocate onchain'},{id:'prizes',icon:'✦',label:'Premi e riserve'},{id:'operations',icon:'⊙',label:'Operazioni'},{id:'swap',icon:'⇄',label:'Swap'},{id:'inventory',icon:'▦',label:'Inventory'},{id:'wallet',icon:'◇',label:'Wallet admin'}];
const gameLabels: Record<string,string> = {waiting:'Attesa blocco',revealable:'Reveal disponibile',expired:'Reveal scaduto',won:'Vinta',lost:'Nessun premio',invalidated:'Invalidata'};
const short = (value:string) => value.slice(0,6)+' ··· '+value.slice(-6);
const usdc = (value:string) => formatUnits(BigInt(value),6);
const displayBalance = (value:string|null) => {if(value===null)return '—';const [integer,decimals='']=value.split('.');return integer+','+decimals.padEnd(2,'0');};
const transactionLink = (hash:string) => 'https://basescan.org/tx/'+hash;
export function AdminWorkspace({account, identity, error, busy, onRefresh, onLogout}: {
  account:AdminAccountView & {wallet:NonNullable<AdminAccountView['wallet']>}; identity:string; error:string; busy:boolean; onRefresh:()=>void; onLogout:()=>void;
}) {
  const [swapBusy,setSwapBusy]=useState(false);
  const wallet=account.wallet, transaction=useContractTransaction(wallet.address,account.userId);
  const walletBalance=displayBalance(wallet.balance.amount);
  const [tab,setTab]=useState<Tab>('overview'), [data,setData]=useState<Data|null>(null), [configured,setConfigured]=useState<boolean|null>(null), [loadError,setLoadError]=useState('');
  const [history,setHistory]=useState<GameView[]>([]), [historyCursor,setHistoryCursor]=useState<string|undefined>(), [nextCursor,setNextCursor]=useState('0');
  const [selected,setSelected]=useState<GameView|null>(null), [action,setAction]=useState<AdminAction>('pause'), [args,setArgs]=useState<string[]>([]), [copied,setCopied]=useState(false);
  const reload=useCallback(async()=>{
    try {
      const response=await fetch('/api/contract?view=admin&player='+wallet.address,{cache:'no-store',signal:AbortSignal.timeout(25000)});
      const value=await response.json(); if(!response.ok)throw new Error(value.error||'Lettura onchain non disponibile.');
      setConfigured(value.configured);setData(value.configured?value:null);setLoadError('');
    } catch(cause){setLoadError(cause instanceof Error?cause.message:'Connessione onchain interrotta.');}
  },[wallet.address]);
  useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;async function poll(){await reload();if(!stopped)timer=setTimeout(poll,10000);}void poll();return()=>{stopped=true;clearTimeout(timer);};},[reload]);
  useEffect(()=>{if(transaction.confirmed){void reload();onRefresh();}},[transaction.confirmed]);
  useEffect(()=>{
    if(!data||tab!=='games')return;
    let cancelled=false;
    fetch('/api/contract?view=history'+(historyCursor?'&before='+historyCursor:''),{cache:'no-store',signal:AbortSignal.timeout(25000)}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!cancelled){setHistory(value.games);setNextCursor(value.next);setSelected(previous=>previous?value.games.find((game:GameView)=>game.id===previous.id)||previous:null);}}).catch(cause=>{if(!cancelled)setLoadError(cause instanceof Error?cause.message:'Storico non disponibile.');});
    return()=>{cancelled=true;};
  },[tab,historyCursor,data?.block,transaction.confirmed]);
  const definition=ADMIN_ACTIONS.find(item=>item.name===action)!;
  const target=ADMIN_TARGETS.find(item=>item.id===definition.target)!;
  const visibleActions=ADMIN_ACTIONS.filter(item=>account.role==='owner'||OPERATOR_ACTIONS.includes(item.name));
  const permitted=!!data&&account.operationsEnabled&&(action!=='mintERC1155'||!!account.mintEnabled)&&(account.role==='owner'||OPERATOR_ACTIONS.includes(action))&&(definition.role==='any'||definition.role==='owner'&&data.permissions?.isOwner||definition.role==='manager'&&data.permissions?.manager||definition.role==='treasurer'&&data.permissions?.treasurer||definition.role==='pauser'&&data.permissions?.pauser);
  function chooseAction(value:AdminAction,preset:string[]=[]){setAction(value);setArgs(preset);setTab('operations');}
  async function copy(){try{await navigator.clipboard.writeText(wallet.address);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setLoadError('Seleziona e copia l’indirizzo completo.');}}
  function table(rows:GameView[]){return <div className="session-table-wrap"><table className="session-table"><thead><tr><th>Giocata / wallet</th><th>Tipo</th><th>Stato</th><th>Premio effettivo</th><th><span className="sr-only">Dettagli</span></th></tr></thead><tbody>{rows.map(game=><tr key={game.id}><td><strong>#{game.id}</strong><span>{short(game.player)}</span></td><td>{game.freeSpin?'FREE SPIN':'USDC'}</td><td><span className={'session-badge '+(game.pending?'active':game.won?'active':game.invalidated?'expired':'ended')}>{gameLabels[game.status]}</span></td><td>{game.payout?game.payout.formattedAmount+' '+(game.payout.kind===3?'free spin':game.payout.tokenSymbol||SYMBOLS[game.winningSymbol]):'—'}</td><td><button className="table-action" aria-label={'Dettagli giocata '+game.id} onClick={()=>setSelected(game)}>↗</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-result"><h3>Nessuna giocata.</h3><p>Le giocate compariranno dopo la conferma onchain.</p></div>}</div>;}
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="admin-brand" href="/admin"><span aria-hidden="true">✳</span><b>LUCKY<br/>SIGNAL<sup>®</sup></b></a><span className="sidebar-label">CONTROL ROOM / ONCHAIN</span><nav aria-label="Sezioni admin">{navigation.map(item=><button key={item.id} aria-current={tab===item.id?'page':undefined} className={tab===item.id?'selected':''} onClick={()=>setTab(item.id)}><span aria-hidden="true">{item.icon}</span>{item.label}{tab===item.id&&<i/>}</button>)}</nav><div className="sidebar-foot"><div className="operator-mini"><span>↗</span><div><b>{account.role==='owner'?'Proprietario wallet':'Collaboratore'}</b><small>{short(wallet.address)}</small></div></div><button className="sidebar-logout" onClick={onLogout}>Esci dall’account <span>↗</span></button><a href="/">Apri il terminale ↗</a></div></aside>
    <main className="admin-main"><header className="admin-topbar"><span>OPERATOR SPACE <b>/ {navigation.find(item=>item.id===tab)?.label.toUpperCase()}</b></span><span className="real-badge">● WALLET CONDIVISO</span></header><div className="admin-page-heading"><div><span className="eyebrow">YOUR ARCADE. GOOD SIGNAL.</span><h1>{tab==='overview'?'Tutto al suo posto.':tab==='games'?'Ogni giro, onchain.':tab==='prizes'?'La fortuna ha un premio.':tab==='operations'?'Ai comandi.':tab==='swap'?'Dalle crypto ai premi.':tab==='inventory'?'Il tuo stock di fortuna.': 'Il wallet del vostro arcade.'}</h1><p>{tab==='wallet'?'Un indirizzo, un saldo e le ricariche condivise. Su Base.':tab==='swap'?'Acquista i token dal wallet condiviso e prepara i prossimi premi.':tab==='inventory'?'Token nel wallet e premi da depositare nella slot, su Base.':'Stato, permessi e risultati letti direttamente dal contratto.'}</p></div><span className="heading-star" aria-hidden="true">✳</span></div>
      {(error||loadError)&&<div className="admin-error" role="alert">{error||loadError}<button className="admin-text" disabled={busy} onClick={()=>{void reload();onRefresh();}}>Aggiorna</button></div>}
      {transaction.error&&<div className="admin-error" role="alert">{transaction.error}</div>}
      {transaction.pending&&<div className="admin-feedback" role="status"><span>Richiesta in verifica{transaction.gasToken?' · gas '+transaction.gasToken:''}. {transaction.hash&&<a href={transactionLink(transaction.hash)} target="_blank" rel="noreferrer">Vedi su Base ↗</a>}</span><button className="admin-text" disabled={transaction.busy} onClick={()=>void transaction.check()}>Verifica</button></div>}
      {data?.keeper.pendingTransaction&&<div className="admin-feedback" role="status">Wallet backend · transazione in attesa. <a href={transactionLink(data.keeper.pendingTransaction)} target="_blank" rel="noreferrer">Vedi su Base ↗</a></div>}
      {!['wallet','swap','inventory'].includes(tab)&&!data&&<section className="admin-card contract-empty"><span className="eyebrow">{configured===false?'PRONTO PER IL DEPLOY':'CONNESSIONE ONCHAIN'}</span><h2>{configured===false?'Colleghiamo la macchina.':'Leggiamo il contratto…'}</h2><p>{configured===false?'Il contratto non è ancora deployato. Dopo il deploy, indirizzo e blocco iniziale abiliteranno letture, giocate e gestione.':'Attendi la lettura della configurazione.'}</p><p className="fine-print">Il tuo wallet Privy è già disponibile. I dati della macchina appariranno dalla blockchain.</p><button className="admin-secondary" onClick={()=>setTab('wallet')}>Apri il tuo wallet ↗</button></section>}
      {data&&tab==='overview'&&<>
        <div className="chain-strip"><span className="real-badge">● BASE</span><code>{short(data.address)}</code><span>Blocco {data.block}</span><button className="admin-text" onClick={()=>void reload()}>Aggiorna ↻</button></div>
        <div className="metrics"><article><span className="metric-label">MACCHINA <i>↗</i></span><strong>{data.settings.paused?'In pausa':!data.funding?'Verifica':!data.funding.ready?'Da rifornire':'Attiva'}<span className={'metric-dot '+(data.settings.paused?'paused':'')}/></strong><small>{data.settings.configuredPrizeCount} simboli configurati</small></article><article><span className="metric-label">BIGLIETTO <i>◇</i></span><strong>{usdc(data.settings.ticketPrice)}<small>USDC</small></strong><small>Prezzo corrente onchain</small></article><article><span className="metric-label">GIOCATE PENDENTI <i>▤</i></span><strong>{data.settings.activeRoundCount}</strong><small>{(BigInt(data.settings.nextGameId)-1n).toString()} giocate totali</small></article><article className="real-metric"><span className="metric-label">SALDO CONDIVISO <i>◇</i></span><strong>{walletBalance}<small>USDC</small></strong><button onClick={()=>setTab('wallet')}>Apri wallet su Base ↗</button></article></div>
        <div className="overview-columns"><section className="admin-card"><div className="card-heading"><h2>Macchina e probabilità</h2><span className="real-badge">ONCHAIN</span></div><div className="settings-facts"><div><span>Tabella completa</span><b>{data.settings.totalOutcomeWeight/10}% / 100%</b></div><div><span>Senza premio</span><b>{data.settings.noWinWeight/10}%</b></div><div><span>Attesa</span><b>{data.settings.revealDelayBlocks} blocchi</b></div><div><span>Finestra reveal</span><b>{data.settings.revealWindowBlocks} blocchi</b></div><div><span>Versione catalogo</span><b>{data.settings.catalogVersion}</b></div></div><button className="admin-secondary" disabled={!account.operationsEnabled||!data.permissions?.pauser} onClick={()=>chooseAction(data.settings.paused?'unpause':'pause')}>{data.settings.paused?'Riattiva':'Metti in pausa'} ↗</button></section>
        <section className="admin-card keeper-card"><div className="card-heading"><h2>Wallet backend</h2><span className={'session-badge '+(data.keeper.configured?'active':'expired')}>{data.keeper.configured?'Configurato':'Da configurare'}</span></div><p>Conclude i reveal e usa i free spin per i player.</p><code>{data.keeper.address||'SLOT_BACKEND_PRIVATE_KEY non impostata'}</code><div className="settings-facts"><div><span>Saldo per il gas</span><b>{formatUnits(BigInt(data.keeper.balanceWei),18)} ETH</b></div><div><span>Ultimo blocco verificato</span><b>{data.keeper.lastBlock}</b></div><div><span>Ruolo per i free spin</span><b>{data.keeper.canStartFreeSpin?'Abilitato':'Manca GAME_MANAGER_ROLE'}</b></div></div>{data.keeper.error&&<p className="admin-error">{data.keeper.error}</p>}{data.keeper.address&&account.role==='owner'&&data.permissions?.isOwner&&!data.keeper.canStartFreeSpin&&<button className="admin-secondary" onClick={()=>chooseAction('grantRole',[keccak256(toHex('GAME_MANAGER_ROLE')),data.keeper.address!])}>Autorizza free spin backend ↗</button>}</section></div>
        <section className="admin-card"><div className="card-heading"><h2>Permessi del wallet condiviso</h2><span className="real-badge">LETTI DAL CONTRATTO</span></div><div className="role-chips">{['isOwner','manager','treasurer','pauser'].map(role=><span key={role} className={data.permissions?.[role as keyof NonNullable<Data['permissions']>]?'enabled':''}>{role==='isOwner'?'Owner':role}</span>)}</div><p className="fine-print">Ogni operazione richiede il ruolo onchain corrispondente e una conferma del tuo wallet Privy.</p></section>
      </>}
      {data&&tab==='games'&&<section className="admin-card"><div className="card-heading"><h2>Registro giocate</h2><span className="real-badge">CONTRATTO + EVENTI</span></div>{table(history)}<div className="history-pagination"><button className="admin-text" disabled={!historyCursor} onClick={()=>setHistoryCursor(undefined)}>← Più recenti</button><button className="admin-text" disabled={BigInt(nextCursor)<=1n} onClick={()=>setHistoryCursor(nextCursor)}>Precedenti ↗</button></div></section>}
      {data&&tab==='prizes'&&<><div className="chain-strip"><span>Probabilità totali: <b>{data.settings.totalOutcomeWeight/10}%</b></span><span>Senza premio: <b>{data.settings.noWinWeight/10}%</b></span></div><div className="prize-grid">{data.catalog.map(prize=>{const stock=data.inventory.find(value=>value.symbol===prize.symbol);return <article className="admin-card prize-card" key={prize.symbol}><header><img src={'/symbols/symbol-'+prize.symbol+'.svg'} alt=""/><div><span className="eyebrow">SIMBOLO {prize.symbol}</span><h2>{SYMBOLS[prize.symbol]}</h2><span className="session-badge">{prize.kind===1?'ERC20':prize.kind===2?'ERC1155':'FREE SPIN'}</span></div></header><div className="settings-facts"><div><span>Probabilità 3/5 · 5/5</span><b>{prize.threeMatchWeight/10}% · {prize.fiveMatchWeight/10}%</b></div><div><span>Premio 5/5 (unità minime)</span><b>{prize.fiveMatchAmount}</b></div><div><span>Premio 3/5 (unità minime)</span><b>{prize.threeMatchWeight?prize.kind===1?(BigInt(prize.fiveMatchAmount)/2n).toString():prize.fiveMatchAmount:'—'}</b></div>{stock&&<><div><span>Riserva totale · impegnata</span><b>{stock.balance} · {stock.reserved}</b></div><div><span>Disponibile (unità minime)</span><b>{stock.available}</b></div></>}</div>{prize.kind!==3&&<code>{prize.token}{prize.kind===2?' / ID '+prize.tokenId:''}</code>}<button className="admin-text" disabled={!account.operationsEnabled||!data.permissions?.manager} onClick={()=>chooseAction('configurePrize',[String(prize.symbol),String(prize.kind),prize.token,prize.tokenId,prize.fiveMatchAmount,String(prize.threeMatchWeight),String(prize.fiveMatchWeight)])}>Modifica premio ↗</button></article>;})}</div>{!data.catalog.length&&<section className="admin-card"><h2>Il catalogo è vuoto.</h2><p>Configura almeno tre simboli e completa il totale al 100% prima di aprire le giocate.</p><button className="admin-secondary" disabled={!account.operationsEnabled||!data.permissions?.manager} onClick={()=>chooseAction('configurePrize')}>Configura un premio ↗</button></section>}</>}
      {data&&tab==='operations'&&<div className="operations-layout"><section className="admin-card settings-card"><div className="card-heading"><h2>Operazione onchain</h2><span className="real-badge">PRIVY ADMIN</span></div><label className="operation-label" htmlFor="admin-action">Cosa vuoi fare?</label><select id="admin-action" value={action} disabled={transaction.busy||transaction.pending||swapBusy} onChange={event=>chooseAction(event.target.value as AdminAction)}>{ADMIN_TARGETS.map(group=>{const items=visibleActions.filter(item=>item.target===group.id);return items.length?<optgroup key={group.id} label={group.label}>{items.map(item=><option key={item.name} value={item.name}>{item.label}</option>)}</optgroup>:null;})}</select><p className="operation-target-note"><b>{target.label}</b> · {target.note}</p><form onSubmit={event=>{event.preventDefault();void transaction.execute(action,args).catch(()=>{});}}>{definition.fields.map((label,index)=><label className="operation-field" key={action+index}>{label}<input value={args[index]||''} required disabled={transaction.busy||transaction.pending||swapBusy} onChange={event=>setArgs(previous=>{const next=[...previous];next[index]=event.target.value.trim();return next;})}/></label>)}{!permitted&&<p className="admin-error">Il tuo accesso o i ruoli del wallet non consentono questa operazione.</p>}<div className="operation-review"><span className="eyebrow">FIRMA DAL TUO WALLET</span><code>{short(wallet.address)}</code><p>{definition.label} · {target.label} · rete Base</p><small>{data.gasMode==='usdc'?'Gas in USDC dal tuo wallet; fallback in ETH se gli USDC non bastano.':'Il gas viene pagato in ETH dal tuo wallet.'}</small></div><button className="admin-primary" type="submit" disabled={!permitted||transaction.busy||transaction.pending||swapBusy||!!loadError}>{transaction.busy?'Conferma in corso…':'Simula e conferma con Privy'} <span>↗</span></button></form></section><section className="admin-card operation-notes"><span className="eyebrow">DAL CONTRATTO</span><h2>Ogni modifica è una transazione.</h2><p>Prezzo, premi e tempi possono cambiare solo senza giocate pendenti. Per prelevare serve anche la pausa.</p><p>I pesi devono sommare a 1000: un’unità vale lo 0,1%. Gli importi token sono nelle unità minime indicate dai campi.</p><h3>Ruoli bytes32</h3>{['GAME_MANAGER_ROLE','TREASURER_ROLE','PAUSER_ROLE'].map(role=><div className="role-value" key={role}><span>{role}</span><code>{keccak256(toHex(role))}</code></div>)}<p>Owner: <code>{data.permissions?.owner}</code></p>{data.pendingOwner&&data.pendingOwner.address!=='0x0000000000000000000000000000000000000000'&&<p>Trasferimento in attesa verso <code>{data.pendingOwner.address}</code>, accettabile dal timestamp {data.pendingOwner.schedule}.</p>}</section></div>}
      {tab==='wallet'&&<div className="wallet-layout"><section className="admin-card admin-wallet-card"><div className="card-heading"><h2>Wallet condiviso</h2><span className="real-badge">● REALE · BASE</span></div><span className="eyebrow">SALDO DISPONIBILE</span><div className="admin-wallet-balance">{walletBalance} <span>USDC</span></div><p className="balance-freshness">{error||wallet.balance.stale?'Ultimo saldo disponibile · aggiornamento in attesa':'Saldo letto sulla rete Base'}</p><button className="admin-text" disabled={busy} onClick={onRefresh}>{busy?'Aggiornamento…':'Aggiorna saldo ↻'}</button><div className="account-details"><span>IL TUO ACCESSO PRIVY</span><p>{identity}</p><span>INDIRIZZO WALLET</span><code>{wallet.address}</code><button className="admin-secondary" onClick={()=>void copy()}>{copied?'Indirizzo copiato ✓':'Copia indirizzo ↗'}</button></div><p className="fine-print">Questo wallet firma le operazioni del team. Nella sezione Inventory trovi affiancati i saldi del wallet e quelli del contratto, con deposito e mint dei premi.</p></section><section className="admin-card admin-receive"><span className="eyebrow">USDC / BASE MAINNET</span><h2>Fai il pieno.</h2><p>Ricevi USDC sulla rete Base.</p><img src={wallet.depositQr} width={220} height={220} alt="QR indirizzo del wallet admin su Base"/><code>{wallet.address}</code><span className="receive-network">● BASE · USDC</span><p className="fine-print">Il deposito arriva al wallet condiviso ed è disponibile anche agli altri admin autorizzati.</p></section></div>}
      <AdminAssets tab={tab} address={wallet.address} userId={account.userId} slot={data} contractBusy={transaction.busy||transaction.pending} canDeposit={account.operationsEnabled} onDeposit={transaction.execute} onRefresh={onRefresh} onSwapBusy={setSwapBusy} onConfigure={asset=>chooseAction('configurePrize',[String(asset.symbol),'1',asset.address,'0','','',''])}/>
      {tab==='wallet'&&<AdminTeam account={account} onRefresh={onRefresh}/>}
      <footer className="admin-footer">LUCKY SIGNAL / CONTROL ROOM <span>EST. 2026 ✦</span></footer>
    </main>
    <TransactionConfirmation review={transaction.review} onDecision={transaction.decide}/>
    {selected&&<div className="admin-modal-backdrop"><section className="admin-session-dialog" role="dialog" aria-modal="true" aria-labelledby="game-detail-title" onKeyDown={event=>{if(event.key==='Escape')setSelected(null);if(event.key==='Tab'){const links=event.currentTarget.querySelectorAll<HTMLElement>('button,a');const first=links[0],last=links[links.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}}><div className="card-heading"><span className="real-badge">ONCHAIN</span><button className="table-action" autoFocus aria-label="Chiudi dettagli" onClick={()=>setSelected(null)}>×</button></div><h2 id="game-detail-title">Giocata #{selected.id}</h2><code className="game-player-address">{selected.player}</code><div className="settings-facts"><div><span>Stato</span><b>{gameLabels[selected.status]}</b></div><div><span>Target / deadline</span><b>{selected.targetBlock} / {selected.revealDeadline}</b></div><div><span>Catalogo</span><b>v{selected.catalogVersion}</b></div><div><span>Premio</span><b>{selected.payout?selected.payout.formattedAmount+' '+(selected.payout.tokenSymbol||SYMBOLS[selected.winningSymbol]):'—'}</b></div></div>{selected.hasResult&&selected.confirmed&&<div className="result-mini-grid">{selected.symbols.map((symbol,index)=><img key={index} src={'/symbols/symbol-'+symbol+'.svg'} alt={SYMBOLS[symbol]}/>)}</div>}{selected.transactionHash&&<a className="admin-text" href={transactionLink(selected.transactionHash)} target="_blank" rel="noreferrer">Reveal su BaseScan ↗</a>}</section></div>}
  </div>;
}
